### ISSUE TITLE
LANGUAGE CHANGE

### ISSUE THREAD

**Issue by wapmastaz** [daffahaidar/school-management-system#1]
Very Good Job...I have a project to create school management system, then I found yours, would like to use it, but how would I change the langauge to english.

**Comment by daffahaidar** [comment]
Incidentally the language used by me to make the program uses Indonesian. So if you want to change it to English you can translate it manually

**Comment by daffahaidar** [comment]
Or you can view the course from scratch by buying it here 
https://www.udemy.com/course/laravel-advanced-course-build-school-management-system/
